kafka:
  bootstrap-server:
    url: http://kafka.confluent.svc.cluster.local:9092
  schema-registry:
    url: http://schemaregistry.confluent.svc.cluster.local:8081
  topic: jokes-test
api:
  url: https://api.chucknorris.io/jokes/random
server:
  port: 8095